package com.shaun.foodnut.utils

object Constants {
    val HEALTH_LABELS = listOf(
        "alcohol-free",
        "celery-free",
        "crustacean-free",
        "dairy-free",
        "egg-free",
        "fish-free",
        "fodmap-free",
        "gluten-free",
        "immuno-supportive",
        "keto-friendly",
        "kidney-friendly",
        "kosher",
        "low-fat-abs",
        "low-potassium",
        "low-sugar",
        "lupine-free",
        "Mediterranean",
        "mustard-free",
        "no-oil-added",
        "paleo",
        "peanut-free",
        "pescatarian",
        "pork-free",
        "red-meat-free",
        "sesame-free",
        "shellfish-free",
        "soy-free",
        "sugar-conscious",
        "tree-nut-free",
        "vegan",
        "vegetarian",
        "wheat-free",
    )

    val FOOD_CATEGORIES = listOf(
        "generic-foods",
        "generic-meals",
        "packaged-foods",
        "fast-foods"
    )
    val NUTRIENT_TYPES = listOf(
        "nutrients[CA]",
        "nutrients[CHOCDF]",
        "nutrients[CHOLE]",
        "nutrients[FAMS]",
        "nutrients[FAPU]",
        "nutrients[FASAT]",
        "nutrients[FAT]",
        "nutrients[FATRN]",
        "nutrients[FE]",
        "nutrients[FIBTG]",
        "nutrients[FOLDFE]",
        "nutrients[K]",
        "nutrients[MG]",
        "nutrients[NA]",
        "nutrients[ENERC_KCAL]",
        "nutrients[NIA]",
        "nutrients[P]",
        "nutrients[PROCNT]",
        "nutrients[RIBF]",
        "nutrients[SUGAR]",
        "nutrients[THIA]",
        "nutrients[TOCPHA]",
        "nutrients[VITA_RAE]",
        "nutrients[VITB12]",
        "nutrients[VITB6A]",
        "nutrients[VITC]",
        "nutrients[VITD]",
        "nutrients[VITK1]",
    )
}